apiVersion: batch/v1
kind: CronJob
metadata:
  name: trading-bot
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
          - name: ghcr-secret
          containers:
          - name: bot
            image: ghcr.io/terabyite/trading-bot:latest