apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trading-bot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Terabyite/Crypto-Bot-Platform.git
    targetRevision: main
    path: manifests/bot
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true